site_name: NoteBooks

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Neetcode 150:
      - Arrays & Hashing: Neetcode 150/Arrays & Hashing.md
      - Two Pointers: Neetcode 150/Two Pointers.md
      - Sliding Window: Neetcode 150/Sliding Window.md
      - Stack: Neetcode 150/Stack.md
      - Binary Search: Neetcode 150/Binary Search.md
      - Linked List: Neetcode 150/Linked List.md
      - Trees: Neetcode 150/Trees.md
      - Heap / Priority Queue: Neetcode 150/Priority Queue(Heap).md
      - Backtracking: Neetcode 150/Backtracking.md
      - Tries: Neetcode 150/Tries.md
      - Graphs: Neetcode 150/Graphs.md
      - Advanced Graphs: Neetcode 150/Advanced Graphs.md
      - 1-D Dynamic Programming: Neetcode 150/1-D Dynamic Programming.md
      - 2-D Dynamic Programming: Neetcode 150/2-D Dynamic Programming.md
      - Greedy: Neetcode 150/Greedy.md
      - Intervals: Neetcode 150/Intervals.md
      - Math & Geometry: Neetcode 150/Math & Geometry.md
      - Bit Manipulation: Neetcode 150/Bit Manipulation.md

  - Full Stack:
      - React: Full Stack/React.md
      - SQL: Full Stack/SQL.md
      - Backend: Full Stack/Backend.md
      - Web Notes: Full Stack/Web Notes.md
      - nginx: Full Stack/nginx.md
  - Systems:
      - OS: Systems/OS.md
      - OSlab: Systems/OSlab.md
      - CSAPP: Systems/CSAPP.md
