site_name: NoteBooks

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Algorithms:
      - Templates: Algorithms/Templates.md
      - Arrays & Hashing: Algorithms/Arrays & Hashing.md
      - Two Pointers: Algorithms/Two Pointers.md
      - Sliding Window: Algorithms/Sliding Window.md
      - Stack: Algorithms/Stack.md
      - Binary Search: Algorithms/Binary Search.md
      - Linked List: Algorithms/Linked List.md
      - Trees: Algorithms/Trees.md
      - Heap / Priority Queue: Algorithms/Priority Queue(Heap).md
      - Backtracking: Algorithms/Backtracking.md
      - Tries: Algorithms/Tries.md
      - Graphs: Algorithms/Graphs.md
      - Advanced Graphs: Algorithms/Advanced Graphs.md
      - 1-D Dynamic Programming: Algorithms/1-D Dynamic Programming.md
      - 2-D Dynamic Programming: Algorithms/2-D Dynamic Programming.md
      - Greedy: Algorithms/Greedy.md
      - Intervals: Algorithms/Intervals.md
      - Math & Geometry: Algorithms/Math & Geometry.md
      - Bit Manipulation: Algorithms/Bit Manipulation.md
      - Simulation: Algorithms/Simulation.md
  - Full Stack:
      - Software Engineering: Full Stack/Software Engineering.md
      - React: Full Stack/React.md
      - SQL: Full Stack/SQL.md
      - Backend: Full Stack/Backend.md
      - Web Notes: Full Stack/Web Notes.md
      - nginx: Full Stack/nginx.md
  - Systems:
      - OS: Systems/OS.md
      - OSlab: Systems/OSlab.md
      - CSAPP: Systems/CSAPP.md
  - Design Patterns:
      - Design Principles (SOLID): Design Patterns/SOLID.md
      # - Behavioral Patterns: Design Patterns/Behavioral Patterns.md
      # - Creational Patterns: Design Patterns/Creational Patterns.md
      - Structual Patterns:
          - Proxy: Design Patterns/Structual Patterns/Proxy.md
          - Chain of Responsibility: Design Patterns/Structual Patterns/Chain of Responsibility.md
